openapi: 3.0.0
info:
  version: '1.0.0-Beta-1'
  title: bkg_ntf_v1.0.0-Beta-1
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/booking-notifications:
    post:
      summary: ''
      operationId: post-v1-booking-notifications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingNotification'
      responses:
        '204':
          description: No Content
      servers:
        - url: 'http://localhost:3000'
components:
  schemas:
    BookingNotification:
      type: object
      title: BookingNotification
      properties:
        specversion:
          type: string
          enum:
            - '1.0'
          example: '1.0'
        id:
          type: string
          maxLength: 100
          example: 3cecb101-7a1a-43a4-9d62-e88a131651e2
        source:
          type: string
          maxLength: 4096
          example: 'https://member.com/'
        type:
          type: string
          enum:
            - org.dcsa.bookingnotification.v1
          example: 'org.dcsa.bookingnotification.v1'
        time:
          type: string
          example: '2018-04-05T17:31:00Z'
        datacontenttype:
          type: string
          enum:
            - application/json
          example: 'application/json'
        data:
          type: object
          properties:
            bookingStatus:
              type: string
            carrierBookingReference:
              type: string
            carrierBookingRequestReference:
              type: string
          required:
            - bookingStatus
      required:
        - specversion
        - id
        - source
        - type
        - time
