openapi: 3.0.0
x-stoplight:
  id: a6iz4bb3dw0lc
info:
  title: DCSA OpenAPI specification for Operational Reefer Monitoring
  version: 1.0.0-Beta-1
  contact:
    name: Digital Container Shipping Association (DCSA)
    email: info@dcsa.org
    url: 'https://dcsa.org'
  license:
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    name: Apache 2.0
  description: |-
    Exchange data uniformly on data collected from live reefers between operational supply chain partners such as carriers, terminals and vessel operators.

    For explanation to specific values or objects please refer to the [Information Model 2023.Q1](https://dcsa.org/wp-content/uploads/2022/02/DCSA-Information-Model-2023.Q1.pdf).

    There are two ways to get events. Either they can be **polled by you** or they can be **pushed to an endPoint** by the implementor.

    ## Poll model
    Polling data can be done using

        GET /v1/events

    Calling this endPoint will return a list of events that fulfill the query parameters specified. The list returned is sorted in ascending (`ASC`) order based on the creation date-time of the event (`eventCreatedDateTime`). **This endPoint is mandatory to implement.**

    ## Push model
    Having events pushed to you is possible via setting up a subscription, **DR to update here the latest push endpoint** 

    For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/blob/master/reeferXXXXX). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

    **@todo add the github url once established in above DR**
tags:
  - name: Events
    description: Event operations
paths:
  /events:
    get:
      tags:
        - Events
      summary: Retrieve Reefer Information
      operationId: fetchReefer
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/3.1.0#/components/parameters/eventDateTime'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/3.1.0#/components/parameters/equipmentReference'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/3.1.0#/components/parameters/reeferEventTypeCodes'
        - schema:
            type: boolean
          in: query
          name: activeControllerAlarms
          description: Will filter by all live reefers with one or more active alarms
      description: Fetch the current monitoring data available for reefer container fleet
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reeferResponse'
              examples:
                'Reefer data related to equipmentReference: ''APZU4812090''':
                  description: |
                    To retrieve the reefer data for a specific `equipmentReference` the following request could be made:

                        GET /events?equipmentReference=APZU4812090
                        
                  value:
                    payload:
                      activeAlarmCount: 0
                      controller:
                        dateTime: '2023-10-23T15:40:28Z'
                        hardwareVersion: 1.1.1
                        maker: 900
                        model: N99
                        operatingState: 1
                        serialNumber: '123456789'
                        softwareVersion: 1.1.1
                      equipmentReference: APZU4812090
                      equipmentOptions:
                        - N00
                        - N05
                      isConnectedToPowerSource: true
                      lastDefrost: '2023-10-23T15:40:28Z'
                      measurements:
                        ambientTemperature: 12
                        temperature: 5
                        temperatureUnit: CEL
                        o2: 20
                        co2: 25
                        relativeHumidity: 98
                        airExchange: 0
                        airExchangeUnit: MQH
                        cargoProbe1Temperature: 6
                        cargoProbe2Temperature: 6
                        cargoProbe3Temperature: 6
                        currentPhaseA: 15
                        currentPhaseB: 15
                        currentPhaseC: 15
                        dischargePressure: 21
                        dischargeTemperature: 10
                        evaporatorTemperature: 10
                        lineFrequency: 60
                        lineVoltage: 400
                        returnProbe1Temperature: 10
                        returnProbe2Temperature: 10
                        returnTemperature: 10
                        suctionPressure: 60
                        suctionTemperature: 10
                        supplySensor1Temperature: 10
                        supplySensor2Temperature: 10
                        supplyTemperature: 10
                      setpoints:
                        temperature: -15
                        temperatureUnit: CEL
                        o2: 20
                        co2: 25
                        humidity: 96
                      reeferSettings:
                        controlledAtmosphereMode: 'ON'
                        defrosting: false
                        efficiencySetting: '2'
                      unitModel: N00
        default:
          description: Unexpected error
          headers:
            API-Version:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/headers/API-Version'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/ERROR_DOMAIN/2.0.0#/components/schemas/error'
                  - type: object
                    properties:
                      httpMethod:
                        example: GET
                  - type: object
                    properties:
                      requestUri:
                        example: 'https://dcsa.org/dcsa/tnt/v1/events'
      x-stoplight:
        id: k62mkncefaldt
components:
  schemas:
    measurements:
      type: object
      x-stoplight:
        id: ab808f3b8e601
      properties:
        ambientTemperature:
          $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredAmbientTemperature'
        temperature:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
        temperatureUnit:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/temperatureUnit'
        o2:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredO2'
        co2:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredCo2'
        relativeHumidity:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredHumidity'
        airExchange:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredAirExchange'
        airExchangeUnit:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/airExchangeUnit'
        cargoProbe1Temperature:
          type: number
          format: float
          example: 6
        cargoProbe2Temperature:
          type: number
          format: float
          example: 6
        cargoProbe3Temperature:
          type: number
          format: float
          example: 6
        cargoProbe4Temperature:
          type: number
          x-stoplight:
            id: 3dkqi3m46ix4l
          format: float
        currentPhaseA:
          $ref: '#/components/schemas/currentPhaseA'
        currentPhaseB:
          $ref: '#/components/schemas/currentPhaseB'
        currentPhaseC:
          $ref: '#/components/schemas/currentPhaseC'
        dischargePressure:
          $ref: '#/components/schemas/dischargePressure'
        dischargeTemperature:
          $ref: '#/components/schemas/dischargeTemperature'
        evaporatorTemperature:
          $ref: '#/components/schemas/evaporatorTemperature'
        lineFrequency:
          $ref: '#/components/schemas/lineFrequency'
        lineVoltage:
          $ref: '#/components/schemas/lineVoltage'
        returnProbe1Temperature:
          $ref: '#/components/schemas/returnProbe1Temperature'
        returnProbe2Temperature:
          $ref: '#/components/schemas/returnProbe2Temperature'
        returnTemperature:
          $ref: '#/components/schemas/returnTemperature'
        suctionPressure:
          $ref: '#/components/schemas/suctionPressure'
        suctionTemperature:
          $ref: '#/components/schemas/suctionTemperature'
        supplySensor1Temperature:
          $ref: '#/components/schemas/supplySensor1Temperature'
        supplySensor2Temperature:
          $ref: '#/components/schemas/supplySensor2Temperature'
        supplyTemperature:
          $ref: '#/components/schemas/supplyTemperature'
      title: Measurements
    reeferResponse:
      type: object
      x-stoplight:
        id: 1101e866d0266
      properties:
        alarms:
          $ref: '#/components/schemas/alarms'
        controller:
          $ref: '#/components/schemas/controller'
        equipmentReference:
          $ref: '#/components/schemas/equipmentReference'
        equipmentOptions:
          $ref: '#/components/schemas/equipmentOptions'
        geoLocation:
          $ref: '#/components/schemas/geoLocation'
        isConnectedToPowerSource:
          type: boolean
          description: 'Indicates if the source is connected to power, aligned to COA UDM P2'
        lastDefrost:
          $ref: '#/components/schemas/lastDefrost'
        measurements:
          $ref: '#/components/schemas/measurements'
        setpoints:
          $ref: '#/components/schemas/setpoints'
        reeferSettings:
          $ref: '#/components/schemas/reeferSettings'
        unitModel:
          $ref: '#/components/schemas/unitModel'
    reeferSettings:
      type: object
      x-stoplight:
        id: 89583c1e5a249
      properties:
        controlledAtmosphereMode:
          $ref: '#/components/schemas/controlledAtmosphereMode'
        defrosting:
          $ref: '#/components/schemas/defrosting'
        efficiencySetting:
          $ref: '#/components/schemas/efficiencySetting'
    setpoints:
      type: object
      x-stoplight:
        id: 4db10b053cb8e
      properties:
        temperature:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
        temperatureUnit:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/temperatureUnit'
        o2:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredO2'
        co2:
            - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredCo2'
        humidity:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: |
            The percentage of the controlled atmosphere humidity target value
          example: 95.6
    controller:
      type: object
      x-stoplight:
        id: 425fbc59eb757
      properties:
        dateTime:
          $ref: '#/components/schemas/controllerDateTime'
        hardwareVersion:
          $ref: '#/components/schemas/controllerHardwareVersion'
        maker:
          $ref: '#/components/schemas/controllerMaker'
        model:
          $ref: '#/components/schemas/controllerModel'
        operatingState:
          $ref: '#/components/schemas/controllerOperatingState'
        serialNumber:
          $ref: '#/components/schemas/controllerSerialNumber'
        softwareVersion:
          $ref: '#/components/schemas/controllerSoftwareVersion'
    controlledAtmosphereMode:
      type: string
      x-stoplight:
        id: 78e1cd0fd35b0
      description: The controlled atmosphere mode setting
    equipmentReference:
      type: string
      x-stoplight:
        id: 466cdf45dc3cd
      pattern: ^\S+(\s+\S+)*$
      maxLength: 11
      description: |
        The unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible.
        According to ISO 6346, a container identification code consists of a 4-letter prefix and a 7-digit number (composed of a 3-letter owner code, a category identifier, a serial number, and a check-digit).

        If a container does not comply with ISO 6346, it is suggested to follow [Recommendation #2: Containers with non-ISO identification](https://smdg.org/documents/smdg-recommendations) from SMDG.
      example: APZU4812090
    alarms:
      type: object
      x-stoplight:
        id: ed63afe9afbf6
      properties:
        activeAlarmCount:
          type: integer
          description: The number of active alarms from the controller
        activeAlarms:
          type: array
          items:
            type: object
            properties:
              alarmDate:
                type: string
                format: date-time
                description: The datetime of when the alarm first appeared
              alarmNumber:
                type: string
                x-stoplight:
                  id: 961e16039a0db
                description: Harmonised Alarm Code across all Manufacturers
    controllerDateTime:
      type: string
      x-stoplight:
        id: bafc1d5c43922
      format: date-time
      description: The datetime from the controller device
    controllerHardwareVersion:
      type: string
      x-stoplight:
        id: ed36279a8a5b7
      description: The hardware revision of the controller device
    controllerMaker:
      type: string
      x-stoplight:
        id: c1515e242e9ef
      description: The manufacturers of source equipment such as reefer controllers
    controllerModel:
      type: string
      x-stoplight:
        id: 7cc87f90608a2
      description: The model of the controller from the maker
    controllerOperatingState:
      type: string
      x-stoplight:
        id: 9c4d3615d5a9e
      description: 'The controller operating state, specific to the type of controller'
    controllerSerialNumber:
      type: string
      x-stoplight:
        id: 85198024f8ff2
      description: The serial number of the controller device
    controllerSoftwareVersion:
      type: string
      x-stoplight:
        id: 6c473aa909c95
      description: The software version running on the controller device
    currentPhaseA:
      type: number
      x-stoplight:
        id: 8a465afd81161
      format: float
      description: The phase A current or average current in Amps
    currentPhaseB:
      type: number
      x-stoplight:
        id: 8a765afd81a78
      format: float
      description: The phase B current in Amps
    currentPhaseC:
      type: number
      x-stoplight:
        id: 8a665afd81d8f
      format: float
      description: The phase C current in Amps
    defrosting:
      type: boolean
      x-stoplight:
        id: 458de0f8230ef
      description: Indicates if the device is defrosting
    dischargePressure:
      type: number
      x-stoplight:
        id: 49290aca593bd
      format: float
      description: The discharge pressure in BarRelative units
    dischargeTemperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: c404ba92de724
      description: The discharge temperature
    efficiencySetting:
      type: number
      x-stoplight:
        id: a1beb5769dd83
      description: The efficiency Setting (controller specific) COA UDM List 5.5.8
    evaporatorTemperature:
      type: number
      x-stoplight:
        id: 6272d1f6f40b4
      format: float
      description: The evaporator temperature in CEL
    equipmentOptions:
      type: array
      x-stoplight:
        id: bf9a1437488d6
      description: List of equipment options available on the container
      items:
        type: string
    geoLocation:
      type: object
      x-stoplight:
        id: cc01ff8a61d52
      properties:
        latitude:
          type: number
          example: 48.85855
        longitude:
          type: number
          example: 2.294492036
    lastDefrost:
      type: string
      x-stoplight:
        id: 2a7068aedfe2d
      format: date-time
      description: The end time of the past defrost period
    lineFrequency:
      type: number
      x-stoplight:
        id: 6e4b52aa20d93
      format: float
      description: The mains power frequency in Hz
      example: 50
    lineVoltage:
      type: number
      x-stoplight:
        id: 61ca68123fe58
      format: float
      description: The mains power voltage in volts
      example: 400
    returnProbe1Temperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: 6934ad00380e2
      description: The return temperature of probe 1
    returnProbe2Temperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: abd348f9ff713
      description: The return temperature of probe 2
    returnTemperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: dd36cf48be38d
      description: The return temperature
    suctionPressure:
      type: number
      x-stoplight:
        id: 3b087c8448ec4
      format: float
      description: The suction pressure in BarRelative units
    suctionTemperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: 835659bfe7a60
      description: The suction temperature
    supplySensor1Temperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: 271ce9a039642
      description: The supply sensor 1 temperature
    supplySensor2Temperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: 4cdb64e4f91bb
      description: The supply sensor 2 temperature
    supplyTemperature:
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.0.0#/components/schemas/measuredTemperature'
      x-stoplight:
        id: c9ece89b02cdf
      description: The supply temperature
    unitModel:
      type: string
      x-stoplight:
        id: 81e5c104a750f
      description: 'The unit model specific to the maker, COA UDM 5.5.3 code list'
