openapi: 3.1.0
x-stoplight:
  id: 6e9471512b4ab
info:
  title: DCSA Components
  description: |
    Common header components for DCSA APIs.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: 'https://dcsa.org'
    email: info@dcsa.org
  version: ''
components:
  headers:
    API-Version:
      schema:
        type: string
        example: 1.0.0
      description: |
        SemVer used to indicate the version of the contract (API version) returned.
  parameters:
    APIVersionHeader:
      name: API-Version
      in: header
      description: SemVer used to indicate the version of the contract (API version) returned.
      schema:
        type: string
    Limit:
      name: limit
      in: query
      description: Maximum number of items to return.
      schema:
        type: number
        minimum: 0
        default: 100